name: CI-CD

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'

jobs: 
  TestCode:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        working-directory: src
    
      - name: Run the tests
        run: npm test
        working-directory: src

  BuildAndPush:
    runs-on: ubuntu-latest
    needs: TestCode
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
              ${{ runner.os }}-buildx-
  
        
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: src
          file: src/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/end-api:latest

  DeployToAzure:
    runs-on: ubuntu-latest
    needs: BuildAndPush
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to Azure Container Instance
        uses: azure/aci-deploy@v1
        with: 
          resource-group: myresourcegroup  
          dns-name-label: end-api-aydin  
          image: ${{ secrets.DOCKER_USERNAME }}/end-api:latest  
          registry-login-server: docker.io
          name: end-api-container
          location: Southeast Asia 
          ports: 3000
          cpu: 0.5
          memory: 1.5

